using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTicketType : Migration
    {
        // Up/Down hand-curated to the TicketType delta ONLY (template:
        // 20260606170000_AddGalleryProvenance). EF's auto-scaffold additionally diffed
        // pre-existing EnsureCreated-applied entities (DJMix/Playlist/EventOrganizerApplication
        // and several columns) that were never captured in a prior migration; those are an
        // out-of-scope, pre-existing snapshot drift and are intentionally excluded here so
        // this migration is surgical. The Designer + ModelSnapshot (regenerated by EF) carry
        // the full, correct target model so future `migrations add` diffs cleanly.
        // CHECK constraint uses double-quoted identifiers — valid on both SQLite and Postgres.

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "TicketTypes",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    EventId = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    PriceMinor = table.Column<long>(nullable: false),
                    VATRate = table.Column<decimal>(nullable: false),
                    Currency = table.Column<string>(nullable: false),
                    Capacity = table.Column<int>(nullable: false),
                    QuantitySold = table.Column<int>(nullable: false),
                    QuantityHeld = table.Column<int>(nullable: false),
                    AdmitCount = table.Column<int>(nullable: false),
                    MinPerOrder = table.Column<int>(nullable: false),
                    MaxPerOrder = table.Column<int>(nullable: false),
                    SalesStart = table.Column<DateTime>(nullable: true),
                    SalesEnd = table.Column<DateTime>(nullable: true),
                    Status = table.Column<int>(nullable: false),
                    SortOrder = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TicketTypes", x => x.Id);
                    // Oversell backstop — provider-neutral quoted identifiers.
                    table.CheckConstraint(
                        "CK_TicketType_Capacity",
                        "\"QuantitySold\" + \"QuantityHeld\" <= \"Capacity\"");
                    table.ForeignKey(
                        name: "FK_TicketTypes_Events_EventId",
                        column: x => x.EventId,
                        principalTable: "Events",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_TicketTypes_EventId",
                table: "TicketTypes",
                column: "EventId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TicketTypes");
        }
    }
}
